# Generated by Django 4.2.9 on 2024-05-31 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HorseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('owner', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JockeyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RaceResultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(max_length=50)),
                ('horse_name_position', models.CharField(max_length=50)),
                ('odds', models.CharField(max_length=50)),
                ('margin', models.CharField(max_length=50)),
                ('race_name', models.CharField(max_length=50)),
                ('video_comment', models.TextField()),
                ('steward_comment', models.TextField()),
                ('barrior_horse_number', models.CharField(max_length=50)),
                ('last_600m_race_time', models.CharField(max_length=50)),
                ('race_time', models.CharField(max_length=50)),
                ('position_at_800m', models.CharField(max_length=50)),
                ('conditions', models.TextField()),
                ('class_of_race', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TrackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TrailResultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_trail', models.CharField(max_length=50)),
                ('track_name', models.CharField(max_length=50)),
                ('distance', models.CharField(max_length=50)),
                ('conditions', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('race_time', models.CharField(max_length=50)),
                ('horse_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TrainerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('list_horses', models.TextField()),
            ],
        ),
    ]
