# Generated by Django 5.0.6 on 2024-05-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TreeModel',
            fields=[
                ('id', models.BigIntegerField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('currentID', models.IntegerField(max_length=10)),
                ('parrentID', models.IntegerField(max_length=10)),
                ('currentName', models.CharField(max_length=50)),
                ('background', models.CharField(max_length=50)),
                ('note', models.TextField()),
                ('fontSize', models.CharField(max_length=10)),
            ],
        ),
    ]
